### ISSUE TITLE
Current Error

### ISSUE THREAD

**Issue by DaleNaci** [DaleNaci/CodeGolfScores#1]
Here is what we get when running main.py

```
Uwu We made a fucky wucky! A wittle fucko boingo! The code monkeys at our headquarters are working VEWY HARD to fix this!
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    print(scores.score_dict(names, problems))
  File "/Users/dalenash/Desktop/GitHub/CodeGolfScores/scores.py", line 14, in score_dict
    for row in html.find_all('tr'):
AttributeError: 'str' object has no attribute 'find_all
```

**Comment by Peter-Lande** [comment]
Code is working fine now. Closing issue.
